### ISSUE TITLE
add mentions légales

### ISSUE THREAD

**Issue by philippeBron** [cristianpb/covid-19-certificate#14]
Add administrative information as in https://www.interieur.gouv.fr/Infos-du-site/Mentions-legales
delete all information that are not relevant for the application and update team and contact.

**Comment by philippeBron** [comment]
Is it mandatory if the application is referenced in the official page https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire-et-justificatif-de-deplacement-professionnel ?

**Comment by infosteph** [comment]
Ne fait-on finalement pas une page mentions légales spécifique en reprenant les informations sur l'éditeur dans la page mentions légales du ministère et en adaptant le reste ? Je peux y travailler.
