### ISSUE TITLE
Calendar icone doesn't works

### ISSUE THREAD

**Issue by philippeBron** [cristianpb/covid-19-certificate#27]
Calendars icons a side the date fields seems clickable as a datepicker but doesn't open any calendar.

- [ ] deactivate the icon and add a placeholder in order to show the date format

**Comment by cristianpb** [comment]
In my case, the icon opens the calendar, is this maybe a compatibility issue ? 

Are we talking about the icon in the image ? 

![2020-03-27_16:03:38](https://user-images.githubusercontent.com/18708179/77769965-d4e3b000-7044-11ea-8cd9-a7aa84ed9195.png)

**Comment by philippeBron** [comment]
yes this date-selector
it works only on firefox for me (not on chrome, edge or brave that are all based on chromium)
