### ISSUE TITLE
Accessibility : warn the user if a new window is opened

### ISSUE THREAD

**Issue by infosteph** [cristianpb/covid-19-certificate#71]
For all pages opened in a new window or a new tab target="_blank", mention "new window" in the title of the <a> tag

**Comment by philippeBron** [comment]
J'avais fait dans la PR #66

**Comment by infosteph** [comment]
Désolé. Dans ce cas, il manque l'info dans le lien de confidentialité car nous avons fait le choix (à ce stade) de l'ouvrir dans une nouvelle fenêtre.

**Comment by philippeBron** [comment]
ok il n'était pas dans une nouvelle fenêtre au moment de la PR.
